### ISSUE TITLE
Create interface for emailing users

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#19]
Each user should have an "email this user" box, to allow email from in the interface. 

This will do a few things.

Add a new records to a database table called email_messages (Class EmailMessage).  It will then use activejob to queue a worker to send the email. Users should always get a copy of the email they sent, so that a conversation can occur with the reply all.

database columns

to: comma seperated list of email addresses
from: current_user (link)
message_body: textual message body

Main goals: learn active job! http://edgeguides.rubyonrails.org/active_job_basics.html

**Comment by dvito** [comment]
From the old system.

![screen shot 2015-01-22 at 12 18 47 pm](https://cloud.githubusercontent.com/assets/1225922/5921400/b0f4ae04-a611-11e4-9522-57cb31f854d3.png)

**Comment by Mgitim** [comment]
The email interface has been built and tested. I haven't added the button to "Send all admins an email" because we have no way of distinguishing between regular users and admins as of now. I will do that once we talk to the clients and add the "admin indicative" attribute.
