### ISSUE TITLE
jquery tokeninput in admin forms

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#24]
Looking at include jquery token input 
http://loopj.com/jquery-tokeninput/

for agencies, tags, and contacts tied to social media accounts / mobile applications.

do you see any issue with that stylisticall @srudra. do you have any preferences in tokeninput plugins?

**Comment by srudra** [comment]
I do not see any issues, I can match the styles according to digitalgov.gov theme.

**Comment by dvito** [comment]
this has been started. styling is complete, need to integrate as needed
