### ISSUE TITLE
Social Media Outlet History View

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#4]
Swtich to a panel based view (bootstrap panels)

Each panel should have  the full information of the social media registration (similar to the show view).  

Each panel should have a restore button to restore the item to that state.

**Comment by Mgitim** [comment]
Switched to bootstrap panel based view
Each panel has full information of the social media registration, exactly like the show view.
Each panel has its restore link pulled to the right of the email of the person who made those changes.
