### ISSUE TITLE
Go through and make html consistent

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#63]
We have inconsistent nesting of html.

We should ensure divs with class="container"  contain divs with class "row".  Divs with class "row" should contain divs with class "col".  Col divs should have content in them. They can further have more rows and columns, but nested structure should be consistent across pages.

Though not "broken", it makes consistency of spacing an issue.

**Comment by srudra** [comment]
Sure.

Shreyasi Rudra
srudra@ctacorp.com mailto:smacfarland@ctacorp.com

ctac
3120 Fairview Park Drive, Suite 600
Falls Church, VA  22042
www.ctacorp.com http://www.ctacorp.com/

**Comment by Mgitim** [comment]
This is done but it's pending a second set of eyes from Shreyasi just to make sure I didn't miss anything.
