### ISSUE TITLE
Admin: Simple text search

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#66]
Add simple text search to the social media, mobile apps, galleries pages.  Should search account name, url, description fields (use LIKE queries for now).

**Comment by isadr** [comment]
This is done. Although, we may need to fix the status message to reflect that the results are from a search. Currently it says:  "Displaying all 30 mobile products".  And the "all" is there even if it's not actually all of them :-)  Not sure where to make the fix though.

**Comment by dvito** [comment]
It comes from page_entries_info. Leave it for now in my opinion unless it
seems easy to alter
