### ISSUE TITLE
Admin: Pagination Size

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#68]
Infinite scroll or custom pagination size (preferred)

**Comment by dvito** [comment]
use 10, 25, 50, 100

**Comment by isadr** [comment]
This is for the results on the search page right?  http://localhost:3000/search

**Comment by dvito** [comment]
For the pages at:

localhost:3000/admin/social_media
localhost:3000/admin/mobile_apps
localhost:3000/admin/galleries

**Comment by isadr** [comment]
By "localhost:3000/admin/social_media"  .. you mean  "localhost:3000/admin/outlets" ... right?

**Comment by dvito** [comment]
Need to add the pagination options to mobile products / galleries Still @ctaraider

**Comment by isadr** [comment]
Doh ...  how'd I miss those.  Will get em in.

**Comment by isadr** [comment]
This should be done.
