### ISSUE TITLE
Move icons are misleading

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#72]
We may need to discuss this issue

**Comment by dvito** [comment]
I've added a short blurb, will look for test from stakeholders.

**Comment by srudra** [comment]
Okay.
Shreyasi Rudra
srudra@ctacorp.com mailto:smacfarland@ctacorp.com

ctac
3120 Fairview Park Drive, Suite 600
Falls Church, VA  22042
www.ctacorp.com http://www.ctacorp.com/
