### ISSUE TITLE
Add the ability to search the user list

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#79]
Create a dropdown for agency, and a text box for search (that will go against first/last/email).

**Comment by isadr** [comment]
Should the dropdown fire on selection? Or will the search button take care of that?  Also, should first and last name be displayed in the results table?

**Comment by dvito** [comment]
nah, just use them as search fields, most of the time their email will
include both anyway

**Comment by isadr** [comment]
Ready for Shreyasi
