### ISSUE TITLE
Make the tables show the full value for a field, with wrapping to a new line if need be.

### ISSUE THREAD

**Issue by dvito** [ctacdev/social-media-registry#82]
In the various administrative portions, can we do something so values in the table are not cut off, but wrap to a new line?

**Comment by srudra** [comment]
I will take a look.

Shreyasi Rudra
srudra@ctacorp.com mailto:smacfarland@ctacorp.com

ctac
3120 Fairview Park Drive, Suite 600
Falls Church, VA  22042
www.ctacorp.com http://www.ctacorp.com/
